library(ggplot2)
library("faraway", lib.loc="~/R/win-library/3.4")
require(faraway)
data(cheddar)
cheeseMod = lm(taste~Acetic+H2S+Lactic,cheddar)
summary(cheeseMod)
cheeseModP = lm(taste~exp(Acetic)+exp(H2S)+Lactic,cheddar)
summary(cheeseModP)
anova(cheeseMod,cheeseModP)
data(sat)
scores = lm(total~expend+ratio+salary,sat)
scoresSZ = lm(total~expend+ratio,sat)
scoresNull=lm(total~1,sat)
anova(scores,scoresSZ)
anova(scores,scoresNull)
summary(scores)
tscores = lm(total~expend+ratio+salary+takers,sat)
anova(tscores,scores)
summary(tscores)
data(prostate)
proModel = lm(lpsa~lcavol+lweight+age+lbph+svi+lcp+gleason+pgg45,prostate)
summary(proModel)
predict(proModel,new=data.frame(lcavol=1.44692,lweight=3.62301,age=65.00,lbph=0.30010,svi=0.0,lcp=-0.79851,gleason=7.0,pgg45=15),interval="prediction")
predict(proModel,new=data.frame(lcavol=1.44692,lweight=3.62301,age=20.00,lbph=0.30010,svi=0.0,lcp=-0.79851,gleason=7.0,pgg45=15),interval="prediction")
median(prostate$age)
newModel = lm(lpsa~lcavol+lweight+svi,prostate)
predict(newModel,new=data.frame(lcavol=1.44692,lweight=3.62301,age=65.00,lbph=0.30010,svi=0.0,lcp=-0.79851,gleason=7.0,pgg45=15),interval="prediction")
predict(newModel,new=data.frame(lcavol=1.44692,lweight=3.62301,age=20.00,lbph=0.30010,svi=0.0,lcp=-0.79851,gleason=7.0,pgg45=15),interval="prediction")
data(fat)
fatModel = lm(brozek~age+weight+height+abdom,fat)
summary(fatModel)
summary(lm(brozek~.,fat))

smallData = data.frame(fat$age,fat$weight,fat$height,fat$abdom)
smallData[25:50,]
updatedData = smallData[-c(39,41),]
newfatModel = lm(brozek~age+weight+height+abdom,data=fat[-c(39,41),])
vals = model.matrix(newfatModel)
medians = apply(vals,2,median)
predict(newfatModel,new=data.frame(t(medians)),interval = "prediction")
vif(fat)
fullFatModel = lm(brozek~.,fat)
fatMatrix = model.matrix(fullFatModel)[,-1] #NOTE: this -1 is to remove intercept value of 1
eVals = eigen(t(fatMatrix)%*%fatMatrix)
sqrt(eVals$val[1]/eVals$val)
vif(fat[-c(39,42)])
fullFatModel = lm(brozek~.,fat[-c(39,42)])
fatMatrix = model.matrix(fullFatModel)[,-1] #NOTE: this -1 is to remove intercept value of 1
eVals = eigen(t(fatMatrix)%*%fatMatrix)
sqrt(eVals$val[1]/eVals$val)
adjustedModel = lm(brozek~age+weight+height,fat)
vif(data.frame(fat$age,fat$weight,fat$height))
fatMatrix = model.matrix(adjustedModel)[,-1] #NOTE: this -1 is to remove intercept value of 1
eVals = eigen(t(fatMatrix)%*%fatMatrix)
sqrt(eVals$val[1]/eVals$val)
vals = model.matrix(adjustedModel)
medians = apply(vals,2,median)[2:4]
predict(adjustedModel,new=data.frame(t(medians)),interval = "prediction")
predict(adjustedModel,new=data.frame(age=40,weight=200,height=73),interval = "prediction")
predict(adjustedModel,new=data.frame(age=40,weight=130,height=73),interval = "prediction")
