library(ggplot2)
library("faraway", lib.loc="~/R/win-library/3.4")
data(cheddar)
cheeseMod = lm(taste~Acetic+H2S+Lactic,cheddar)
summary(cheeseMod)
cheeseModP = lm(taste~exp(Acetic)+exp(H2S)+Lactic,cheddar)
summary(cheeseModP)
anova(cheeseMod,cheeseModP)
data(sat)
scores = lm(total~expend+ratio+salary,sat)
scoresSZ = lm(total~expend+ratio,sat)
scoresNull=lm(total~1,sat)
anova(scores,scoresSZ)
anova(scores,scoresNull)
summary(scores)
tscores = lm(total~expend+ratio+salary+takers,sat)
anova(tscores,scores)
summary(tscores)