data('teengamb')
data(uswages)
data(prostate)
data(cheddar)
library(ggplot2)
males = teengamb[teengamb$sex == 0,]
females = teengamb[teengamb$sex == 1,]
mmean = weighted.mean(males$gamble)
fmean = weighted.mean(females$gamble)
mvar = var(males$gamble)
fvar = var(females$gamble)
png("C:/Users/alexander/Documents/GitHub/regressions/expenses.png")
p = ggplot(teengamb) + geom_point(aes(sex,gamble,shape=sex,color=sex,fill=sex)) + scale_shape_identity() 
p + annotate("text",x=.5,y=75,label = "Variance and expected values for men gambling\n is much higher than woman, study shows") +labs(x="gender",y="pounds gambled per week")
#plot(gamble~sex,teengamb,pch=c(10,20)[(teengamb$sex)],col=c("orange","green")[(teengamb$sex)])
#legend("topleft",legend = teengamb$sex[!duplicated(teengamb$sex)],col=c("orange","green"),pch=c(10,20))
dev.off()
lTG<-lm(gamble ~ sex + status + income + verbal, teengamb)
summary(lTG)
rTG = residuals(lTG)
mTG = max(rTG)
which(rTG==mTG)
weighted.mean(rTG)
fTG = fitted(lTG)
var(rTG,fTG)
var(rTG,teengamb$income)
print(mmean-fmean)
usModel <- lm(wage~educ+exper,uswages)
usLModel <- lm(log(wage)~educ+exper,uswages)
summary(usModel)
summary(usLModel)
vars = names(prostate)
prostateModel = lm(lpsa~lcavol,prostate)
tempS=summary(prostateModel)
rVals = double()
rSE = double()
for( nam in vars)
{
  prostateModel = update(prostateModel, as.formula(paste('~ . +', nam)))
  tempS = (summary(prostateModel))
  print(tempS$r.squared)
  rVals=append(rVals, c(tempS$r.squared))
  rSE=append(rSE,tempS$sigma)
  
}
#need to remove the last elements
rVals = head(rVals,-1)
rSE = head(rSE,-1)
png("C:/Users/alexander/Documents/GitHub/regressions/rVals.png")
qplot(1:8,rVals)
dev.off()
#png("C:/Users/BDVR/Documents/Spring2018/regressions/hw3/rSE.png")
png("C:/Users/alexander/Documents/GitHub/regressions/rSE.png")
qplot(1:8,rSE)
dev.off()

cheeseModel = lm(taste~Acetic + H2S + Lactic, cheddar)
summary(cheeseModel)
cheeseFit = fitted(cheeseModel)
actual = cheddar$taste
corrCheese = cor(actual,cheeseFit)
print(corrCheese^2)
cheeseModelNoInt = lm(taste~Acetic + H2S + Lactic+0, cheddar)
summary(cheeseModelNoInt)
CF = fitted(cheeseModelNoInt)
print(cor(actual,CF)^2)
qrc = qr(cheeseModel)
qrCC = t(qr.Q(qrc)) %*% actual
backsolve(qr.R(qrc),qrCC)